# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Collectiive
description: >- # this means to ignore newlines until "baseurl:"
  Sustainable Open Source for an Open World
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://collectiive.com" # the base hostname & protocol for your site, e.g. http://example.com

social:
- title: twitter
  url: https://twitter.com/collectiively
- title: medium
  url: https://medium.com/collectiive

author:
  name:           'Collectiive'
  twitter:        collectiively
  github:         collectiive
  rss:            feed.xml

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-redirect-from

# Outputting
paginate: 30
paginate_path: /:num/

# Markdown Settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# Archives
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea/

